---
driver:
  name: ec2
  subnet_id: subnet-f1f6acac # development-public-us-east-1b
  security_group_ids:
    - sg-8fea3af9 # ci-testing-vpc
  instance_type: c4.large
  interface: public
  tags:
    Env: public
    Type: test
    Operator: <%= ENV['USER'] %>

transport:
  name: sftp
  ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    driver:
      tags:
        Name: ds-opencv-default-ubuntu-1604
    run_list:
      - recipe[ds_opencv::default]
    attributes:
