---
driver:
  name: ec2
  subnet_id: subnet-f1f6acac # development-public-us-east-1b
  instance_type: c5.large
  tags:
    Env: test
    Type: test
    Operator: <%= ENV['USER'] %>

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    driver:
      tags:
        Name: ds-opencv-default-ubuntu-1604
    run_list:
      - recipe[ds_opencv::default]
    attributes:
