language: ruby
cache:
  directories:
  - "$HOME/.berkshelf"
addons:
  apt:
    sources:
    - chef-stable-trusty
    packages:
    - chefdk
if: (type = pull_request) OR (tag IS present)
before_install:
- openssl aes-256-cbc -K $encrypted_25d68ab26777_key -iv $encrypted_25d68ab26777_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar -xvf secrets.tar -C $HOME
- mv $HOME/.aws/ds_travis_credentials $HOME/.aws/credentials
- echo 'node_name "darksky"' >> $HOME/.chef/knife.rb
- echo "client_key '$HOME/.chef/darksky.pem'" >> $HOME/.chef/knife.rb
- echo 'chef_server_url "https://chef.darksky.net/organizations/darksky"' >> $HOME/.chef/knife.rb
- chmod 600 $HOME/.chef/knife.rb $HOME/.chef/darksky.pem
- chef --version
- eval "$(chef shell-init bash)"
install:
- chef gem install stove
jobs:
  include:
  - stage: test
    script: chef exec delivery local all
  - stage: GitHub Release
    script: echo "Deploying to GitHub releases ..."
    deploy:
      provider: releases
      api_key:
        secure: nHAsrJKmjBaISfPLhP2nb76UyWAj1KR26Yis9hxU9h37kLMqIErT7mTO6aGA/qYNMLNcXLIplXy2qqLT4YxphgdZjLzDNPsXU/66FeEJB9MiBGEAVEyS76GSPtG+iggwtsxCLGz1OmQrM6T0EGD9NbsIY5vO0tsrqKuuK8lvA59Doe/JQlLJCihQYv+AKU4g7jgSswna7x8I0q7OIGH+3fmoTTXJ8/vN4VPI99e3Oa1GZYj84K+RHqY/JiB18KAJkRVjGjE8AB8BSGx5w+RaHSfH4a8CiqJXjQ1NOiLYx4ZFflJXxqHQtzx+wTlgtMazYyEZ87OcAvdeYD+dXr8GI0k61M0O5xqmBiQkkJsjQxZO9kPIX8Gzx3z7d+t0WGojSMiClL7v2bsdbwyV5QpY1BMj81jSwSOrRA0vk4migC/+Rb+wnqhoXNHMVc94NCWaIXLS6w5g28nQCaUL70p4YpzMEozTSpWc3shG/kECxdhV2J8b4O7RJaQ2f7E41JdepY81+N7z9itkB/pgTgjPgQWWLa9nYI4RIJlSwOYMcmveReWWZJ96wYpLJCvlhFJj8Kwn6akqwKl2Q8QANG2E3ycqqLPyBf2++cd7fppsi5nH7eky33UDz/S0zmFzyt1ngpV9G9lFaGl8oXnTW+ChUA9FV61yEveSwNIqThLm3pY=
      skip_cleanup: true
      on:
        tags: true
  - stage: Publish to Supermarket
    script: echo "Uploading to Chef Supermarket ..."
    deploy:
      provider: script
      script: chef exec stove --no-git --username darksky --key $HOME/.chef/darksky.pem
      skip_cleanup: true
      on:
        tags: true
notifications:
  slack:
    secure: U3YDfrgI8V8ns5e69IWhA0K6sCJKO7qkJnmwffANv0u7cADq1hYBmNwNtPIJdPjENUnbw/5YI3jA2oRd9j9Sk++pPSXGN3QIHGFjdA6kVwfN8snJdGC4/cbBv7lCUz5Os/38+jx5sK+RHG47oS6KQzNbsApqhy46H/as+TD4eXkVrSc1hCsEkkx/2rEEzZwzXox+sGWqPybcHDnA0BnE3/70yHhH41AJD3I14pkPeQlQsdQWdz2KRNnUPQZo+5xaP4KeaujyOxsynnfVu2l3gp6vrvdiFy3R4aySQQj9GaRXyTf4f6utP+QCTA0HnM8O+zUUJuLVVi4qWDnSpvi0vDQsAt2fNsaE4pceVQqueKccYR/VqYTF6kRewqJZ+ogdRPUNx+pKtbIogpex9LQAJ4NGeQiI9GC0OdDMpsn8buDMw5B+w+C0iZu9lUNoO5rkM7erQK+WEKmfwuvrA6ciLuHMH9YHwg70AJQCJAFBTcBZ1OLJ22+0854XHEdSj6Oc26FXOgsBaAGrDgRzME5GgNCXYrVFuTRjcnEOuXSbp900nUHUbu2jjotlQI79bZK0kyl3QfzxwxLRNy/H3z4S+YxYhDc8ilCDNvQB9KhtqTTODkPt26cYxrfA6aV9nPEq30a1MZpapAYRyXA5TYogg5GBDtU0ROcrCqack/Dexwg=
